feat: add example with SLZ defaults
terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive pull request #245
Opened 2023-03-14 21:02 UTC by MatthewLemmond

### Description
Adds an example with the default variables used in SLZ, resolves https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive/issues/196

### Types of changes in this PR

#### No release required

- [x] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Added a new example with defaults specific to SLZ

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-03-14 21:06 UTC, MatthewLemmond commented
One thing worth noting here, we currently don't have the variables working in a way that would allow setting the policies on keys so the rotation interval month does not line up with what is created by default in SLZ.

2023-03-15 17:42 UTC, ocofaigh requested changes
We need to add a test for it to ensure example is always working. It doesn’t have to be in `pr_test.go` as it adds no extra functionality test, but add it to `other_test.go` so we test it in contonious test pipeline (when support is added for TIM modules)

2023-03-15 23:25 UTC, ocofaigh approved these changes

2023-03-15 23:25 UTC, merged

2023-05-02 11:26 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive/releases/tag/v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: