feat: update to consume latest terraform-ibm-key-protect
terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive pull request #333
Opened 2023-05-22 16:56 UTC by MatthewLemmond

### Description
Bump provider version to 1.53 in order to consume v2.2.0 of the terraform-ibm-key-protect module

### Types of changes in this PR

#### Changes that affect the core Terraform module or submodules
- [ ] Bug fix
- [ ] New feature
- [x] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Update the required provider constraints and consume the v2.2.0 of [terraform-ibm-modules/terraform-ibm-key-protect](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-05-22 21:56 UTC, MatthewLemmond commented
Created to address the failure to merge in https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive/pull/332

2023-05-23 09:54 UTC, shemau submitted a review, later dismissed
Looks good.

This is good to merge to support key-protect v2.2.0 with the revised 1.53 required provider version.
There should be a new issue to exploit key-protect v2.2.0 access tags feature (added in v2.1.0).
#332 can be closed/cancelled when this is merged.

2023-05-24 08:28 UTC, ocofaigh requested changes
@MatthewLemmond Did you forget to expose the new variables for the new features that came in v2.2.0? (`key_create_import_access_settings`, `key_create_import_access_enabled`, `dual_auth_delete_enabled`, `rotation_interval_month`, `rotation_enabled`). Also you may as well add access tags support too

2023-05-24 20:01 UTC, ocofaigh approved these changes

2023-05-24 20:02 UTC, merged

2023-05-24 20:07 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 4.2.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive/releases/tag/v4.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: